<<<<<<< HEAD
# backend/schemas.py
from pydantic import BaseModel
from typing import List, Optional

# ==========================================
# USERS
# ==========================================
class UserCreate(BaseModel):
    id: str  # The ID generated by Supabase Auth
    display_name: str


class UserUpdate(BaseModel):
    display_name: Optional[str] = None
    location: Optional[str] = None

class BadgeUpdate(BaseModel):
    badges: List[str]

# ==========================================
# BUCKET LIST (The Dream Board)
# ==========================================
class BucketListItemCreate(BaseModel):
    user_id: str
    title: str
    deadline: Optional[str] = None

class BucketListItemUpdate(BaseModel):
    title: Optional[str] = None
    deadline: Optional[str] = None

class BucketGoal(BaseModel): # Used by the AI Onboarding
    title: str
    deadline: str

class OnboardRequest(BaseModel):
    user_id: str
    user_answers: str

# ==========================================
# BUCKETS (The Actionable Events)
# ==========================================

class BucketUpdate(BaseModel):
    title: Optional[str] = None
    category: Optional[str] = None
    event_time: Optional[str] = None
    status: Optional[str] = None

class BucketStatusUpdate(BaseModel):
    status: str 

# ==========================================
# AI & FEEDS
# ==========================================
class DiscoverFeedItem(BaseModel):
    title: str
    category: str
    short_description: str
    estimated_cost: str
    image_keyword: str

class PlanBucketRequest(BaseModel):
    user_id: str
    request_text: str 

class PlannedBucketCard(BaseModel):
    title: str
    location: str
    hours: str
    link: str
    hype_message: str

class PlanBucketFromListRequest(BaseModel):
    user_id: str
    bucket_list_item_id: str


class BucketJoinRequest(BaseModel):
    actor_id: str


class BucketCommentCreate(BaseModel):
    bucket_id: str
    actor_id: str
    content: str


class BucketCommentUpdate(BaseModel):
    actor_id: str
    content: str


class BucketMediaCreate(BaseModel):
    bucket_id: str
    actor_id: str
    media_type: str
    public_url: str
    storage_path: Optional[str] = None
    caption: Optional[str] = None


class BucketMediaDelete(BaseModel):
    actor_id: str

class SearchQuery(BaseModel):
    request_text: str

class BucketDisplay(BaseModel):
    """
    The single source of truth for the Frontend. 
    Every feed, DB query, and AI agent returns this structure.
    """
    # Core Visual Data (Always returned by AI and DB)
    title: str
    category: str 
    description: str # Merges 'short_description' and 'hype_message'
    
    # Contextual Data (AI might fill these in, or they might be null)
    location: Optional[str] = None
    event_time: Optional[str] = None
    estimated_cost: Optional[str] = None
    link: Optional[str] = None
    image_keyword: Optional[str] = "San Diego" 

    # Database Identifiers (Only exist IF saved in Supabase)
    id: Optional[str] = None
    creator_id: Optional[str] = None
    status: Optional[str] = None # 'planned', 'active', 'completed'
    created_at: Optional[str] = None

# We still need this specifically for when the frontend POSTs a new bucket to the DB
class BucketCreate(BaseModel):
    creator_id: str
    title: str
    category: str
    event_time: str
=======
# backend/schemas.py
from pydantic import BaseModel
from typing import List, Optional

# ==========================================
# USERS
# ==========================================
class UserCreate(BaseModel):
    id: str  # The ID generated by Supabase Auth
    display_name: str

class BadgeUpdate(BaseModel):
    badges: List[str]

# ==========================================
# BUCKET LIST (The Dream Board)
# ==========================================
class BucketListItemCreate(BaseModel):
    user_id: str
    title: str
    deadline: Optional[str] = None

class BucketListItemUpdate(BaseModel):
    title: Optional[str] = None
    deadline: Optional[str] = None

class BucketGoal(BaseModel): # Used by the AI Onboarding
    title: str
    deadline: str

class OnboardRequest(BaseModel):
    user_id: str
    user_answers: str

# ==========================================
# BUCKETS (The Actionable Events)
# ==========================================

class BucketUpdate(BaseModel):
    title: Optional[str] = None
    category: Optional[str] = None
    event_time: Optional[str] = None
    status: Optional[str] = None

class BucketStatusUpdate(BaseModel):
    status: str 

# ==========================================
# AI & FEEDS
# ==========================================
class DiscoverFeedItem(BaseModel):
    title: str
    category: str
    short_description: str
    estimated_cost: str
    image_keyword: str

class PlanBucketRequest(BaseModel):
    user_id: str
    request_text: str 

class PlannedBucketCard(BaseModel):
    title: str
    location: str
    hours: str
    link: str
    hype_message: str

class PlanBucketFromListRequest(BaseModel):
    user_id: str
    bucket_list_item_id: str

class SearchQuery(BaseModel):
    request_text: str

class BucketDisplay(BaseModel):
    """
    The single source of truth for the Frontend. 
    Every feed, DB query, and AI agent returns this structure.
    """
    # Core Visual Data (Always returned by AI and DB)
    title: str
    category: str 
    description: str # Merges 'short_description' and 'hype_message'
    
    # Contextual Data (AI might fill these in, or they might be null)
    location: Optional[str] = None
    event_time: Optional[str] = None
    estimated_cost: Optional[str] = None
    link: Optional[str] = None
    image_keyword: Optional[str] = "San Diego" 

    # Database Identifiers (Only exist IF saved in Supabase)
    id: Optional[str] = None
    creator_id: Optional[str] = None
    status: Optional[str] = None # 'planned', 'active', 'completed'
    created_at: Optional[str] = None

# We still need this specifically for when the frontend POSTs a new bucket to the DB
class BucketCreate(BaseModel):
    creator_id: str
    title: str
    category: str
    event_time: str
>>>>>>> 1efdbf137a53b631dd4f44804adca853a5a61fca
    status: str = "planned"